title: AP test
author: phypra
only_build_toc_files: true

execute:
  execute_notebooks: "off"   # keep CI fast; students run examples via Binder if needed

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - tasklist

html:
  favicon: _static/favicon.svg
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  extra_footer: |
    <p>Fußzeile - Text & figures: CC BY 4.0 · Code: MIT</p>
  # extra_css:
  #    - _static/custom.css
  theme:
    options:
      show_navbar_depth: 1
      show_prev_next: false

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.youtube

repository:
  url: https://github.com/phypra/ap
  branch: main
  path_to_book: ""

copyright: "Copyright Test"

#launch_buttons:
#  binderhub_url: https://mybinder.org
#  notebook_interface: classic
